
# Server Port
server:
  port: 8080

  # Encoding
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    # Project
debug: true

# log
logging:
  level:
    org:springframework: warn

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:h2:tcp://localhost/~/fighting
    driver-class-name: org.h2.Driver
    username: sa

    password:

  # Thymeleaf
  thymeleaf:
    enabled: true
    servlet:
      content-type: text/html
    encoding: utf-8
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template: true
    mode: HTML
    template-resolver-order: 0
    check-template-location: true